{% set version = "23.10" %}
{% set name = "helix" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/helix-editor/helix/releases/download/{{ version }}/{{ name }}-{{ version }}-source.tar.xz
  sha256: 4e7bcac200b1a15bc9f196bdfd161e4e448dc670359349ae14c18ccc512153e8

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses

test:
  commands:
    - hx --health
    - hx --health | grep -qv "Runtime directory does not exist"

about:
  home: https://github.com/helix-editor/helix
  summary: A post-modern modal text editor
  license: MPL-2.0
  license_family: Mozilla
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - jonashaag
