{% set version = "24.07" %}
{% set name = "helix" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/helix-editor/helix/releases/download/{{ version }}/{{ name }}-{{ version }}-source.tar.xz
  sha256: 44d9eb113a54a80a2891ac6374c74bcd2bce63d317f1e1c69c286a6fc919922c

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - hx --health
    - hx --health | grep -qv "Runtime directory does not exist"

about:
  home: https://github.com/helix-editor/helix
  summary: A post-modern modal text editor
  license: MPL-2.0
  license_family: Mozilla
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - jonashaag
